# Generated by Django 6.0.3 on 2026-03-13 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Unique Tag or Muzzle ID', max_length=50, unique=True)),
                ('breed', models.CharField(max_length=100)),
                ('age_months', models.IntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('is_insured', models.BooleanField(default=False)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livestock_photos/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
